services:
  app:
    build: .
    container_name: go_auth_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
      - redis
    environment:
      - APP_PORT=${APP_PORT}
      - ENV=${ENV}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - go-auth-net

  db:
    image: postgres:17-alpine
    container_name: go_auth_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go-auth-net

  redis:
    image: redis:7-alpine
    container_name: go_auth_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - go-auth-net

volumes:
  postgres_data:
  redis_data:

networks:
  go-auth-net:
    driver: bridge
